# Generated by Django 4.1.2 on 2022-10-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NetflixShow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=250)),
                ("ReleaseDate", models.DateTimeField()),
                ("Type", models.CharField(max_length=20)),
                ("Rating", models.CharField(max_length=50)),
                ("Quality", models.CharField(max_length=50)),
                ("Starring", models.CharField(max_length=250)),
                ("Category", models.CharField(max_length=50)),
                ("Runtime", models.CharField(max_length=50)),
                ("NetflixId", models.CharField(max_length=10)),
                ("Language", models.CharField(max_length=50)),
                ("Description", models.CharField(max_length=1000)),
            ],
        ),
    ]
