MOVIE_DETAILS = [
 {'imdb': '5.2/10',
  'actors': 'Nesta Cooper, Kate Walsh, John Michael Higgins, Keith Powers',
  'category': '',
  'date_released': '2017-09-08',
  'description': 'When nerdy high of her longtime crush, she of his ex,media ity.',
  'director': 'Fernando Lebrija',
  'language': 'English',
  'netflixid': '80125979',
  'quality': 'SuperHD',
  'rating': 'TV-14',
  'runtime': '99 minutes',
  'title': 'title-1',
  'type': 'Movie'},
 {'actors': 'N/A',
  'category': 'Documentary',
  'date_released': '2022-02-23',
  'description': 'Survivors and insiders, \\ the hunt for the perpetrators.',
  'director': 'Jose Gomez',
  'imdb': '',
  'language': 'English',
  'netflixid': '81568624',
  'quality': None,
  'rating': 'TV-14',
  'runtime': '92 min',
  'title': 'title-2 ',
  'type': 'Movie'},
 {'actors': 'Nina Pearce, Adam Tuominen, Emily Morris, Amy Handley',
  'category': '',
  'date_released': '2017-07-01',
  'description': 'A to reach the top. But with  new ,  win a spot on the .',
  'director': 'Clay Glen',
  'imdb': 'N/A',
  'language': 'English',
  'netflixid': '70290905',
  'quality': 'SuperHD',
  'rating': 'PG',
  'runtime': '95 minutes',
  'title': 'title- 3',
  'type': 'Movie'},
 {'actors': 'Will Forte, Domhnall Gleeson, Emmy Rossum, Martin Mull',
  'category': '',
  'date_released': '2018-01-26',
  'description': 'In a life full of triumph and failure, "National Lampoon" '
                 'co-founder Doug Kenney built a comedy empire, molding pop '
                 'culture in the 1970s.',
  'director': 'David Wain',
  'imdb': None,
  'language': 'English',
  'netflixid': '80107084',
  'quality': 'SuperHD',
  'rating': 'TV-MA',
  'runtime': '101 minutes',
  'title': 'title-  4  ',
  'type': 'Movie'}]

MOVIE_DETAILS_OUTPUT = [{'Category': '',
  'Description': 'When nerdy high of her longtime crush, she of his ex,media '
                 'ity.',
  'Director': 'Fernando Lebrija',
  'Imdb': '5.2',
  'Language': 'English',
  'NetflixId': '80125979',
  'Quality': 'SuperHD',
  'Rating': 'TV-14',
  'ReleaseDate': '2017-09-08',
  'Runtime': '99 minutes',
  'Starring': 'Nesta Cooper, Kate Walsh, John Michael Higgins, Keith Powers',
  'Title': 'title-1',
  'Type': 'Movie'},
 {'Category': 'Documentary',
  'Description': 'Survivors and insiders, \\ the hunt for the perpetrators.',
  'Director': 'Jose Gomez',
  'Imdb': 0.0,
  'Language': 'English',
  'NetflixId': '81568624',
  'Quality': None,
  'Rating': 'TV-14',
  'ReleaseDate': '2022-02-23',
  'Runtime': '92 min',
  'Starring': 'N/A',
  'Title': 'title-2 ',
  'Type': 'Movie'},
 {'Category': '',
  'Description': 'A to reach the top. But with  new ,  win a spot on the .',
  'Director': 'Clay Glen',
  'Imdb': 0.0,
  'Language': 'English',
  'NetflixId': '70290905',
  'Quality': 'SuperHD',
  'Rating': 'PG',
  'ReleaseDate': '2017-07-01',
  'Runtime': '95 minutes',
  'Starring': 'Nina Pearce, Adam Tuominen, Emily Morris, Amy Handley',
  'Title': 'title- 3',
  'Type': 'Movie'},
 {'Category': '',
  'Description': 'In a life full of triumph and failure, "National Lampoon" '
                 'co-founder Doug Kenney built a comedy empire, molding pop '
                 'culture in the 1970s.',
  'Director': 'David Wain',
  'Imdb': 0.0,
  'Language': 'English',
  'NetflixId': '80107084',
  'Quality': 'SuperHD',
  'Rating': 'TV-MA',
  'ReleaseDate': '2018-01-26',
  'Runtime': '101 minutes',
  'Starring': 'Will Forte, Domhnall Gleeson, Emmy Rossum, Martin Mull',
  'Title': 'title-  4  ',
  'Type': 'Movie'}]
